# Generated by Django 5.0.6 on 2024-05-31 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name="Letter",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("letter", models.CharField(max_length=15)),
                ("last_word_count", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "letter",
            },
        ),
        migrations.CreateModel(
            name="Word",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("label", models.TextField()),
                ("transcription", models.TextField(blank=True, null=True)),
                ("link", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Description",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("content", models.TextField()),
                ("sentence", models.TextField(blank=True, null=True)),
                ("source", models.TextField(blank=True, null=True)),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="izohli_uz.category",
                    ),
                ),
            ],
            options={
                "db_table": "description",
            },
        ),
    ]
