# Generated by Django 5.0.6 on 2024-05-31 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("izohli_uz", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="word",
            table="word",
        ),
    ]
