# Generated by Django 5.0.6 on 2024-05-31 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("izohli_uz", "0002_alter_word_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="description",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="letter",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="word",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
